sudo: required
os: linux
dist: trusty
language: node_js
node_js:
  - '8'

addons:
  chrome: stable

#before_install:
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  yarn: true
  directories:
    - www-ng/node_modules

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn global add @angular/cli --no-progress

install:
  - cd www-ng
  - cp src/environments/environment.sample.ts src/environments/environment.ts
  - yarn install --no-progress

script: 
  - yarn lint
#  - yarn build --progress false
  - yarn test --progress false --single-run
